name: OcbElectricityOverhaul

on:
  create:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  push:
    branches:
      - master
      - develop
      - main

jobs:

  compile:
    runs-on: windows-latest
    name: Windows MSVC build

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Call OCB7D2D compiler action
      uses: OCB7D2D/OcbModCompiler@master
      with:
        v7d2d: 'V2.3'
        name: "OcbElectricityOverhaul"
        version: "${{ github.ref_name }}"
        token: "${{ secrets.GITHUB_TOKEN }}"
        OCBTOKEN: "${{ secrets.OCBTOKEN }}"
        release: ${{ github.event_name == 'create' && github.event.ref_type == 'tag' }}
